name: build-appimage

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            autotools-dev \
            automake \
            autoconf \
            autoconf-archive \
            pkg-config \
            libimlib2-dev \
            libx11-dev \
            libxext-dev \
            libxcomposite-dev \
            libxfixes-dev \
            libxrandr-dev
      - name: Compilar scrot
        run: |
          ./autogen.sh || true
          ./configure
          make -j$(nproc)
      - name: Ver binario
        run: |
          ls -l src/
      - name: Ver dependencias
        run: |
          ldd src/scrot
      - name: Preparar AppDir
        run: |
          mkdir -p AppDir/usr/bin
          cp src/scrot AppDir/usr/bin/
          cp doc/scrot.png AppDir/scrot.png
          # Copiar plantilla do repo
          #cp AppDir/scrot.desktop AppDir/
          # Crear ruta para loaders
          mkdir -p AppDir/usr/lib/imlib2/loaders
          # Copiar loaders de Imlib2
          cp -r /usr/lib/x86_64-linux-gnu/imlib2/loaders/* AppDir/usr/lib/imlib2/loaders/
          # Crear AppRun
          cat > AppDir/AppRun <<'EOF'
#!/bin/sh
HERE="$(dirname "$(readlink -f "$0")")"
export LD_LIBRARY_PATH="$HERE/usr/lib:$LD_LIBRARY_PATH"
export IMLIB2_LOADER_PATH="$HERE/usr/lib/imlib2/loaders"
exec "$HERE/usr/bin/scrot" "$@"
EOF

    chmod +x AppDir/AppRun
      - name: Descargar linuxdeploy
        run: |
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy-x86_64.AppImage

#      - name: Construír AppImage
#        run: |
#          ./linuxdeploy-x86_64.AppImage \
#            --appdir AppDir \
#            -e AppDir/usr/bin/scrot \
#            --output appimage

      - name: Construír AppImage
        run: |
          export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
 
          ./linuxdeploy-x86_64.AppImage \
            --appdir AppDir \
            -e AppDir/usr/bin/scrot \
            --library /lib/x86_64-linux-gnu/libImlib2.so.1 \
            --deploy-deps-only AppDir/usr/bin/scrot

          ./linuxdeploy-x86_64.AppImage \
            --appdir AppDir \
            --output appimage

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: scrot-appimage
          path: "*.AppImage"
