name: build-appimage

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            autotools-dev \
            automake \
            autoconf \
            autoconf-archive \
            pkg-config \
            libimlib2-dev \
            libx11-dev \
            libxext-dev \
            libxcomposite-dev \
            libxfixes-dev \
            libxrandr-dev
      - name: Compilar scrot
        run: |
          ./autogen.sh || true
          ./configure
          make -j$(nproc)
      - name: Ver binario
        run: |
          ls -l src/
      - name: Preparar AppDir
        run: |
          mkdir -p AppDir/usr/bin
          cp src/scrot AppDir/usr/bin/
          cp doc/scrot.png AppDir/scrot.png
          # Copiar plantilla do repo
          #cp AppDir/scrot.desktop AppDir/

      - name: Descargar linuxdeploy
        run: |
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy-x86_64.AppImage

      - name: Construír AppImage
        run: |
          ./linuxdeploy-x86_64.AppImage \
            --appdir AppDir \
            -e AppDir/usr/bin/scrot \
            --output appimage

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: scrot-appimage
          path: "*.AppImage"
